# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_auto_20180102_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source_object', models.CharField(max_length=256)),
                ('source_id', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_providing_company', to='common.Company')),
            ],
        ),
        migrations.CreateModel(
            name='VP_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('source_file', models.CharField(max_length=128)),
                ('treated', models.BooleanField(default=False)),
                ('treated_date', models.DateTimeField(blank=True, null=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
