# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_vp_position_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VP_PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
    ]
