# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20180102_1727'),
        ('common', '0007_auto_20180102_1918'),
        ('providers', '0005_vp_positiontypemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsecurity',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_security_currency_rel', to='common.Currency'),
        ),
        migrations.AddField(
            model_name='externalsecurity',
            name='provider_identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='externalsecurity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_security_type_rel', to='security.SecurityType'),
        ),
        migrations.AlterField(
            model_name='externalsecurity',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_security_providing_company', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='externalsecurity',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalsecurity',
            name='source_object',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
