# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20180102_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsecurity',
            name='source_object',
        ),
    ]
