# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_remove_externalsecurity_source_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_history', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='externalsecurity',
            name='provider_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsecurityprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_security_pricing', to='providers.ExternalSecurity'),
        ),
    ]
