# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20171126_1813'),
        ('security', '0005_auto_20180102_1727'),
        ('providers', '0008_auto_20180102_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPortfolioHoldings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_price', models.FloatField(default=0.0)),
                ('external_quantity', models.FloatField(default=0.0)),
                ('internal_price', models.FloatField(default=0.0)),
                ('internal_quantity', models.FloatField(default=0.0)),
                ('external_security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_holding', to='providers.ExternalSecurity')),
                ('internal_security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_holding', to='security.Security')),
            ],
        ),
        migrations.DeleteModel(
            name='VP_Position',
        ),
        migrations.DeleteModel(
            name='VP_PositionType',
        ),
        migrations.DeleteModel(
            name='VP_PositionTypeMap',
        ),
        migrations.AddField(
            model_name='externalportfolioholdings',
            name='holdings',
            field=models.ManyToManyField(related_name='portfolio_holdings_consolidation', to='providers.PortfolioHolding'),
        ),
        migrations.AddField(
            model_name='externalportfolioholdings',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to='portfolio.Portfolio'),
        ),
    ]
