# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20180110_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsecurityprice',
            name='security',
        ),
        migrations.RemoveField(
            model_name='externalsecurity',
            name='source_id',
        ),
        migrations.DeleteModel(
            name='ExternalSecurityPrice',
        ),
    ]
