# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_externalsecurity_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsecurity',
            name='provider_data',
        ),
    ]
