# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20180102_1727'),
        ('common', '0007_auto_20180102_1918'),
        ('portfolio', '0020_auto_20180812_1731'),
        ('providers', '0012_remove_externalsecurity_provider_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('provider_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_link', to='portfolio.Account')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_currency_rel', to='common.Currency')),
                ('potential_matches', models.ManyToManyField(blank=True, related_name='external_account_potential_link', to='portfolio.Account')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_providing_company', to='common.Company')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_type_rel', to='portfolio.AccountType')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAccountHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_quantity', models.FloatField(default=0.0)),
                ('internal_quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_account_holding', to='providers.ExternalAccount')),
                ('internal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_account_holding', to='security.Security')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSecurityHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_price', models.FloatField(default=0.0)),
                ('external_quantity', models.FloatField(default=0.0)),
                ('internal_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('internal_quantity', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioholding',
            name='external_security',
        ),
        migrations.RemoveField(
            model_name='portfolioholding',
            name='internal_security',
        ),
        migrations.RemoveField(
            model_name='externalportfolioholdings',
            name='holdings',
        ),
        migrations.AddField(
            model_name='externalportfolioholdings',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings_provider', to='common.Company'),
        ),
        migrations.AddField(
            model_name='externalsecurity',
            name='potential_matches',
            field=models.ManyToManyField(blank=True, related_name='external_security_potential_link', to='security.Security'),
        ),
        migrations.AlterField(
            model_name='externalportfolioholdings',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings_portfolio', to='portfolio.Portfolio'),
        ),
        migrations.DeleteModel(
            name='PortfolioHolding',
        ),
        migrations.AddField(
            model_name='portfoliosecurityholding',
            name='external_security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_security_holding', to='providers.ExternalSecurity'),
        ),
        migrations.AddField(
            model_name='portfoliosecurityholding',
            name='internal_security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_security_holding', to='security.Security'),
        ),
        migrations.AddField(
            model_name='externalportfolioholdings',
            name='account_holdings',
            field=models.ManyToManyField(related_name='portfolio_holdings_accounts', to='providers.PortfolioAccountHolding'),
        ),
        migrations.AddField(
            model_name='externalportfolioholdings',
            name='security_holdings',
            field=models.ManyToManyField(related_name='portfolio_holdings_securities', to='providers.PortfolioSecurityHolding'),
        ),
    ]
