# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_auto_20180818_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioaccountholding',
            name='internal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_account_holding', to='portfolio.Account'),
        ),
    ]
