# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20180102_1918'),
        ('portfolio', '0020_auto_20180812_1731'),
        ('providers', '0014_auto_20180819_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('external_security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_security', to='providers.ExternalSecurity')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_source', to='providers.ExternalAccount')),
                ('external_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_target', to='providers.ExternalAccount')),
                ('internal_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_operation', to='portfolio.Operation')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_portfolio', to='portfolio.Portfolio')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_provider', to='common.Company')),
            ],
        ),
    ]
