# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_externaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransaction',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
