# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=3)),
                ('default_name', models.CharField(max_length=64)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=3)),
                ('default_name', models.CharField(max_length=64)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=3)),
                ('default_name', models.CharField(max_length=64)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
    ]
