# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='default_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='country',
            name='identifier',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='default_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='currency',
            name='identifier',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='visibilitylevel',
            name='default_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='visibilitylevel',
            name='identifier',
            field=models.CharField(max_length=16),
        ),
    ]
