# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171112_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=128, null=True)),
                ('line_2', models.CharField(max_length=128, null=True)),
                ('zip_code', models.CharField(max_length=16, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(max_length=256)),
                ('creation_date', models.DateField(null=True)),
                ('addresses', models.ManyToManyField(blank=True, to='common.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySubsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subsidiary_company_rel', to='common.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySubsidiaryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(null=True)),
                ('addresses', models.ManyToManyField(blank=True, to='common.Address')),
                ('emails', models.ManyToManyField(blank=True, to='common.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='line_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_type_rel', to='common.PhoneType'),
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=models.ManyToManyField(blank=True, to='common.Phone'),
        ),
        migrations.AddField(
            model_name='email',
            name='address_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_type_rel', to='common.MailType'),
        ),
        migrations.AddField(
            model_name='companysubsidiary',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subsidiary_role_rel', to='common.CompanySubsidiaryRole'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_member_person_rel', to='common.Person'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_member_role_rel', to='common.CompanyMemberRole'),
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, to='common.Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(blank=True, to='common.CompanyMember'),
        ),
        migrations.AddField(
            model_name='company',
            name='phones',
            field=models.ManyToManyField(blank=True, to='common.Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='subsidiary',
            field=models.ManyToManyField(blank=True, related_name='company_subsidiary_rel', to='common.CompanySubsidiary'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_type_rel', to='common.AddressType'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country_rel', to='common.Country'),
        ),
    ]
