# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171112_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='subsidiary',
            new_name='subsidiaries',
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_currency_name', to='common.Currency'),
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
