# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20171112_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='companymemberrole',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='companysubsidiaryrole',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='country',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='currency',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mailtype',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='visibilitylevel',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
    ]
