# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20171112_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
