# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
