# Generated by Django 2.2.1 on 2019-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20180102_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_type_rel', to='common.AddressType'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_country_rel', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_currency_name', to='common.Currency'),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_member_person_rel', to='common.Person'),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_member_role_rel', to='common.CompanyMemberRole'),
        ),
        migrations.AlterField(
            model_name='companysubsidiary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_subsidiary_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='companysubsidiary',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_subsidiary_role_rel', to='common.CompanySubsidiaryRole'),
        ),
        migrations.AlterField(
            model_name='email',
            name='address_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='email_type_rel', to='common.MailType'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='line_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phone_type_rel', to='common.PhoneType'),
        ),
    ]
