# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('inception_date', models.DateField()),
                ('closing_date', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_information', django.contrib.postgres.fields.hstore.HStoreField()),
                ('additional_description', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_bank_company_rel', to='common.Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_currency_rel', to='common.Currency')),
                ('management_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_mgmt_company_rel', to='common.Company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_provider_company_rel', to='common.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_type_rel', to='security.SecurityType'),
        ),
    ]
