# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='provider_identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
