# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_security_provider_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='additional_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='additional_information',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
