# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20180102_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_bank_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='security',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_provider_company_rel', to='common.Company'),
        ),
    ]
