# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20180102_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='identifier',
            field=models.CharField(max_length=128),
        ),
    ]
