# Generated by Django 2.2.1 on 2019-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20180102_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_bank_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='security',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_currency_rel', to='common.Currency'),
        ),
        migrations.AlterField(
            model_name='security',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_mgmt_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='security',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_provider_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_type_rel', to='security.SecurityType'),
        ),
    ]
