# Build python 3.6 env
FROM python:3.6
RUN pip install --upgrade pip
RUN pip install certifi==2017.11.5
RUN pip install chardet==3.0.4
RUN pip install click==6.7
RUN pip install Django==1.11.7
RUN pip install django-cors-headers==2.1.0
RUN pip install django-filter==1.1.0
RUN pip install djangorestframework==3.7.3
RUN pip install et-xmlfile==1.0.1
RUN pip install Flask==0.12.2
RUN pip install idna==2.6
RUN pip install itsdangerous==0.24
RUN pip install jdcal==1.3
RUN pip install Jinja2==2.10
RUN pip install Markdown==2.6.9
RUN pip install MarkupSafe==1.0
RUN pip install numpy
RUN pip install openpyxl==2.5.0
RUN pip install pandas
RUN pip install pika==0.11.2
RUN pip install prompt-toolkit==1.0.15
RUN pip install psycopg2==2.7.3.2
RUN pip install Pygments==2.2.0
RUN pip install pylru==1.0.9
RUN pip install pymongo==3.6.0
RUN pip install python-dateutil==2.6.1
RUN pip install pytz==2017.3
RUN pip install requests==2.18.4
RUN pip install six==1.11.0
RUN pip install urllib3==1.22
RUN pip install wcwidth==0.1.7
RUN pip install Werkzeug==0.14.1
RUN pip install xlrd==1.1.0
# Update aptitude with new repo & Install software
RUN apt-get update
RUN apt-get install -y git
RUN mkdir /opt/applications
RUN git clone https://humblejok:Kernel32!@github.com/humblejok/gso_finance_2 /opt/applications
ADD ./settings.py /opt/applications/gso_finance_2/settings.py
CMD ["python3", "/opt/applications/manage.py", "runserver", "0.0.0.0:8001"]