# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('inception_date', models.DateField()),
                ('closing_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_currency_rel', to='common.Currency')),
            ],
        ),
    ]
