# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('current_amount_local', models.FloatField(default=0.0)),
                ('current_amount_portfolio', models.FloatField(default=0.0)),
                ('include_valuation', models.BooleanField(default=True)),
                ('inception_date', models.DateField()),
                ('closing_date', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('last_computation', models.DateField(null=True)),
                ('additional_information', django.contrib.postgres.fields.hstore.HStoreField()),
                ('additional_description', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.Portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForexOperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('spot_rate', models.FloatField(default=1.0)),
                ('amount', models.FloatField()),
                ('amount_portfolio', models.FloatField(blank=True, null=True)),
                ('amount_management', models.FloatField(blank=True, null=True)),
                ('operation_date', models.DateField()),
                ('value_date', models.DateField()),
                ('additional_information', django.contrib.postgres.fields.hstore.HStoreField()),
                ('additional_description', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('default_name', models.CharField(max_length=128)),
                ('quick_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField()),
                ('investments_portfolio', models.FloatField()),
                ('investments_management', models.FloatField()),
                ('cash_portfolio', models.FloatField()),
                ('cash_management', models.FloatField()),
                ('total_portfolio', models.FloatField()),
                ('total_management', models.FloatField()),
                ('daily_performance', models.FloatField()),
                ('weekly_performance', models.FloatField()),
                ('monthly_performance', models.FloatField()),
                ('quarterly_performance', models.FloatField()),
                ('semester_performance', models.FloatField()),
                ('yearly_performance', models.FloatField()),
                ('inception_performance', models.FloatField()),
                ('investments_performance', models.FloatField()),
                ('fx_performance', models.FloatField()),
                ('investments_weight', models.FloatField()),
                ('cash_weight', models.FloatField()),
                ('movements_cash', models.FloatField()),
                ('movements_negative_cash', models.FloatField()),
                ('movements_positive_cash', models.FloatField()),
                ('movements_loan_cash', models.FloatField()),
                ('movements_investments', models.FloatField()),
                ('movements_investments_fop', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='additional_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='additional_information',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_bank_company_rel', to='common.Company'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_aum_local',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_aum_mgmt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_computation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='logo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mgmt_company_rel', to='common.Company'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_provider_company_rel', to='common.Company'),
        ),
    ]
