# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171112_2124'),
        ('common', '0006_auto_20171112_2033'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='valuation_securities_rel', to='security.Security'),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_status_rel', to='portfolio.OperationStatus'),
        ),
        migrations.AddField(
            model_name='investmentoperation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investmemt_operation_type_rel', to='portfolio.InvestmentOperationType'),
        ),
        migrations.AddField(
            model_name='investmentoperation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investmemt_operation_source', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='investmentoperation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investmemt_operation_target', to='security.Security'),
        ),
        migrations.AddField(
            model_name='forexoperation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_operation_type_rel', to='portfolio.ForexOperationType'),
        ),
        migrations.AddField(
            model_name='forexoperation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forex_operation_source', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='forexoperation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forex_operation_target', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_operation_type_rel', to='portfolio.FinancialOperationType'),
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_operation_source', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_operation_target', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='consolidationportfolio',
            name='included_portfolio',
            field=models.ManyToManyField(blank=True, related_name='conso_included_portfolio_rel', to='portfolio.Portfolio'),
        ),
        migrations.AddField(
            model_name='consolidationportfolio',
            name='reference_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conso_portfolio_reference_rel', to='portfolio.Portfolio'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bank_company_rel', to='common.Company'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_currency_rel', to='common.Currency'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='portfolio_accounts_rel', to='portfolio.Account'),
        ),
    ]
