# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20171112_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='additional_information',
        ),
    ]
