# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20171112_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='additional_information',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='additional_information',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='additional_information',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
