# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
        ('portfolio', '0005_auto_20171112_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_rm_person_rel', to='common.Person'),
        ),
        migrations.AlterField(
            model_name='account',
            name='additional_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
