# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20171126_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
    ]
