# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171112_2033'),
        ('portfolio', '0007_remove_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_bank_company_rel', to='common.Company'),
        ),
    ]
