# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_account_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='identifier',
            field=models.CharField(max_length=128),
        ),
    ]
