# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20180102_1727'),
        ('portfolio', '0009_auto_20171126_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialoperation',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='financialoperation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='financialoperation',
            name='target',
        ),
        migrations.RemoveField(
            model_name='forexoperation',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='forexoperation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='forexoperation',
            name='target',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='target',
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investmemt_operation_type_rel', to='portfolio.FinancialOperationType'),
        ),
        migrations.AddField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='operation',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_security', to='security.Security'),
        ),
        migrations.AddField(
            model_name='operation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_source', to='portfolio.Account'),
        ),
        migrations.AddField(
            model_name='operation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_target', to='portfolio.Account'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='additional_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FinancialOperation',
        ),
        migrations.DeleteModel(
            name='ForexOperation',
        ),
        migrations.DeleteModel(
            name='ForexOperationType',
        ),
        migrations.DeleteModel(
            name='InvestmentOperation',
        ),
        migrations.DeleteModel(
            name='InvestmentOperationType',
        ),
    ]
