# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20180201_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='associated_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_parent', to='portfolio.Operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='identifier',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
