# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20180201_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccountChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=26)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_chain', to='portfolio.Account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_operation_chain', to='portfolio.Operation')),
            ],
        ),
    ]
