# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_moneyaccountchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyaccountchain',
            old_name='amount',
            new_name='account_amount',
        ),
        migrations.AddField(
            model_name='moneyaccountchain',
            name='operation_amount',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=26),
            preserve_default=False,
        ),
    ]
