# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20180201_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_type_rel', to='portfolio.AccountType'),
        ),
    ]
