# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_amount_local',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=26),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_amount_portfolio',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=26),
        ),
    ]
