# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20180201_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_computation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
