# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 21:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20180201_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAccountChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('positions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sec_chain', to='portfolio.Account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_operation_sec_chain', to='portfolio.Operation')),
            ],
        ),
    ]
