# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_securityaccountchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityaccountchain',
            name='account',
        ),
        migrations.RemoveField(
            model_name='securityaccountchain',
            name='operation',
        ),
        migrations.DeleteModel(
            name='SecurityAccountChain',
        ),
    ]
