# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20180225_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='month_to_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='previous_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='quarter_to_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='week_to_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='year_to_date',
            field=models.FloatField(default=0.0),
        ),
    ]
