# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20180102_1918'),
        ('security', '0005_auto_20180102_1727'),
        ('portfolio', '0019_auto_20180317_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_security_position', to='security.Security')),
            ],
        ),
        migrations.AddField(
            model_name='valuation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_source', to='common.Company'),
        ),
    ]
