# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20180812_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityposition',
            name='security',
        ),
        migrations.DeleteModel(
            name='SecurityPosition',
        ),
    ]
