# Generated by Django 2.2.1 on 2019-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20180906_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_bank_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_currency_rel', to='common.Currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_type_rel', to='portfolio.AccountType'),
        ),
        migrations.AlterField(
            model_name='consolidationportfolio',
            name='reference_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conso_portfolio_reference_rel', to='portfolio.Portfolio'),
        ),
        migrations.AlterField(
            model_name='moneyaccountchain',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_chain', to='portfolio.Account'),
        ),
        migrations.AlterField(
            model_name='moneyaccountchain',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_operation_chain', to='portfolio.Operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investmemt_operation_type_rel', to='portfolio.FinancialOperationType'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_security', to='security.Security'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_source', to='portfolio.Account'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_status_rel', to='portfolio.OperationStatus'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_target', to='portfolio.Account'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_bank_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_currency_rel', to='common.Currency'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_mgmt_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_provider_company_rel', to='common.Company'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_rm_person_rel', to='common.Person'),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='valuation_source', to='common.Company'),
        ),
    ]
